<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<base target="_blank">
<title><?=$id['title']?></title>
<meta name="keywords" content="<?=$id['keyword']?>"/>
<meta name="description" content="<?=$id['description']?>"/>
<link href="<?=IMGURL?>static/home/css/style_s.css" rel="stylesheet" type="text/css" />
<link href="<?=IMGURL?>static/home/css/shlist.css" rel="stylesheet" type="text/css" />
<link rel="stylesheet" type="text/css" href="<?=IMGURL?>static/home/css/tpynx_con_list_1011.css"/>
<script type="text/javascript" src="<?=IMGURL?>static/home/js/jquery-1.8.3.min.js"></script>
<script type="text/javascript" src="<?=IMGURL?>static/home/js/lower.js"></script>
<style>
.lb-1r p  .ksxqlist_a{ color:#1390c7; background:#e1eff9; }
.lb-1r p  .del_style{width:0px; }
.mh-tip{color:#999;padding-top:5px;}
.mh-tip2{padding-bottom:5px;text-align: center; color: #FF0000;font-size:14px;line-height:20px;}
.top{ background:#f0ebef; height:23px; margin-top:5px;}
.lftop{ float:left;}
.rftop{ float:right; padding-right:10px;}
.rftop ul a{ height:23px; line-height:23px; margin-left:1px; margin-right:1px;}
</style> 
</head>
<body>
  
<!--head-->
<script src="<?=IMGURL?>static/home/js/header.js" type="text/javascript"></script>
<script type="text/javascript" src="<?=IMGURL?>static/home/js/nav.js"></script>
<!--end head-->
<p class="clr"></p>
<!--main-->
<div class="main">
<?php Yaf_Loader::import(PATH_VIEW . '/include/liucheng.phtml');?>
<p class="clr"></p>

<div class="nav1" style="background-color: #CFEDF8;">
<p>
<?php foreach($navlist as $v){?>
<a href="<?=BASEURL?><?=$v['catpath']?>/"><?=$v['catname']?></a>
<?php } ?>
</p>
</div>


<div class="nav1">
<p style="text-align: left;">
<?php foreach($nav as $key=>$val){?>
<a href="<?=BASEURL?><?=$id['catpath']?>/<?=$val['catpath']?>/"><?=$val['catname']?></a>
<?php } ?>
</p>
</div>
<!-- <div class="ss"><strong>热门搜索：</strong><a href="/dianxian/">癫痫病能治愈吗</a><a href="/dianxian/">癫痫病的最新治疗方法</a><a href="/dianxian/">癫痫病可以治愈吗</a><a href="/dianxian/dxzz/">癫痫病的早期症状</a><a href="/dianxian/dxby/">癫痫病是怎么引起的</a><a href="/dianxian/zzzl/">癫痫病的治疗</a></div> -->

<div class="lb-2">

<?php foreach($catlist as $k=>$v){?>
<div class="wz-3n">
<div class="wz-3na"><span><a href="/<?=$id['catpath']?>/<?=$v['catpath']?>/"><?=$v['catname']?></a></span></div>
<div class="wz-3nb">
<div class="wz-3nc"> <img src="<?=IMGURL?>static/home/img/ww<?=$k?>.jpg" width="181" height="120"/></div>
<ul>
<?php foreach($v[0] as $m){?>
<li><a href="/<?=$id['catpath']?>/<?=$v['catpath']?>/<?=$m['id']?>.html"><?=$m['title']?></a></li>
<?php } ?>
</ul>
<!--<div class="wz-3nd">
<div class="wza"><span>8.8分</span>医院评分</div><div class="wza"><span>11496人</span>评价人次</div>
</div>
<div class="wz-3ne"><a href="#"><img src="<?=IMGURL?>static/home/img/shlb_131213_45.jpg" width="51" height="40" alt=""/> </a></div> -->
</div>
</div>
<?php } ?>

</div>
 
<div class="link" id="link">
    <div class="link_1"><p>友情链接</p></div>
		<div class="link_2">
			<ul>
				<?=$friendurl?>
			</ul>
		</div>
	</div>
<p class="clr"></p>
</div>
<!--end main-->
<p class="clr"></p>
<!--foot-->
<?php Yaf_Loader::import(PATH_VIEW . '/include/foot.phtml');?>
<!--end foot-->
</body>
</html>