<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<base target="_blank">
<title><?=$title['title']?></title>
<meta name="keywords" content="<?=$title['keywords']?>"/>
<meta name="description" content="<?=$title['description']?>"/>
<link href="<?=IMGURL?>static/home/css/style_s.css" rel="stylesheet" type="text/css" />
<link href="<?=IMGURL?>static/home/css/shlist.css" rel="stylesheet" type="text/css" />
<link rel="stylesheet" type="text/css" href="<?=IMGURL?>static/home/css/tpynx_con_list_1011.css"/>
<script type="text/javascript" src="<?=IMGURL?>static/home/js/jquery-1.8.3.min.js"></script>
<script src="<?=IMGURL?>static/home/js/iplookup.js"></script>
<script type="text/javascript" src="<?=IMGURL?>static/home/js/lower.js"></script>
<script src="http://guahao.health.sohu.com/static/home/js/a.js" type="text/javascript"></script>
<style>
.lb-1r p  .ksxqlist_a{ color:#1390c7; background:#e1eff9; }
.lb-1r p  .del_style{width:0px; }
.mh-tip{color:#999;padding-top:5px;}
.mh-tip2{padding-bottom:5px;text-align: center; color: #FF0000;font-size:14px;line-height:20px;}
.top{ background:#f0ebef; height:23px; margin-top:5px;}
.lftop{ float:left;}
.rftop{ float:right; padding-right:10px;}
.rftop ul a{ height:23px; line-height:23px; margin-left:1px; margin-right:1px;}
</style>
</head>
<body>
<!--head-->
<script src="http://124.251.42.232:8030/static/home/js/header.js" type="text/javascript"></script>
<script type="text/javascript" src="http://124.251.42.232:8030/static/home/js/nav.js"></script>
<!--end head-->
<p class="clr"></p>
<!--main-->
<div class="main">
<?php Yaf_Loader::import(PATH_VIEW . '/include/liucheng.phtml');?>
<p class="clr"></p>

<div class="nav1" style="background-color: #CFEDF8;">
<p>
<?php foreach($navlist as $v){?>
<a href="<?=BASEURL?><?=$v['catpath']?>/"><?=$v['catname']?></a>
<?php } ?>
</p>
</div>
<?php if(!empty($nav)){?>
<div class="nav1">
<p style="text-align: left;">
<?php foreach($nav as $key=>$val){?>
<a href="<?=BASEURL?><?=$oname['catpath']?>/<?=$val['catpath']?>/"><?=$val['catname']?></a>
<?php } ?>
</p>
</div>
<?php } ?>
<!-- <div class="ss"><strong>热门搜索：</strong><a href="/dianxian/">癫痫病能治愈吗</a><a href="/dianxian/">癫痫病的最新治疗方法</a><a href="/dianxian/">癫痫病可以治愈吗</a><a href="/dianxian/dxzz/">癫痫病的早期症状</a><a href="/dianxian/dxby/">癫痫病是怎么引起的</a><a href="/dianxian/zzzl/">癫痫病的治疗</a></div> -->
<div class="content">
		<div class="con_l">
			<div class="dqwz">
				<span>您现在所在的位置：</span>
				<?php if(!empty($oname)){?>
				<a href="/<?=$oname['catpath']?>/"><?=$oname['catname']?></a> ->&nbsp;
				<a href="/<?=$tname['name']?>"><?=$tname['catname']?></a>->
				<?php }else{ ?>
					<a href="/<?=$tname['catpath']?>/"><?=$tname['catname']?></a> ->
				<?php } ?>
				<?=$title['title']?>
			</div>
			<div class="wznr">
				<h1><?=$title['title']?></h1>
				<div class="fbsj">发布时间：<?php echo date('Y-m-d H:i:s',$title['inputtime']);?></div>
				<div class="wzly"><span><strong>来源：</strong>
					<?php if(!empty($oname)){?>
					<a href="/<?=$tname['name']?>"><?=$tname['catname']?></a>
					<?php }else{ ?>
					<a href="/<?=$tname['catpath']?>/"><?=$tname['catname']?></a>
					<?php } ?>
				</span></div>
				<div class="nrfl">
					<ul>
						<?php foreach($two_title as $v){?>
						<li><a href="<?=$oname['catpath']?>/<?=$tname['catpath']?>/<?=$v['id']?>.html"><?=$v['title']?></a></li>
						<?php } ?>
					</ul>
				</div>
				<?=$content['content']?>
				<div class="fy">
					<div class="syp"></div>
					<!-- <div class="xyp">下一篇：<a href="/dianxian/dxbnzym/6521055407.html">癫痫病的治疗误区有哪些</a></div> -->
				</div>
				<div class="tag">本文地址：<span><?=BASEURL?><?=$tname['name']?><?=$title['id']?>.html</span>
				</div>
				<div class="tag">特别说明：<span>【<?=$title['title']?>】内容仅供参考，医学是严谨的，生命是宝贵的，因个体差异不同，请勿将本网站信息当做诊疗依据!</span></div>
			</div>
			<!--相关文章-->
			<div class="xgwz">
				<h3><?=$title['title']?>的相关文章</h3>
				<div class="nr">
					<ul>
						<?php foreach($one_content as $val){?>
							<li><a href="/<?=$catkey[$val['catid']]['name']?><?=$val['id']?>.html"><?=$val['title']?></a></li>
						<?php } ?>
					</ul>
				</div>
			</div>
			<!--相关文章 end-->
		</div>
		<!--right-->
		<?php Yaf_Loader::import(PATH_VIEW . '/include/right.phtml');?>
		<!--end right-->
	</div>
    <div style="height:20px;"></div>
    <div class="link" id="link">
		<div class="link_1"><p>友情链接</p></div>
		<div class="link_2">
			<ul>
				<?=$friendurl?>
			</ul>
		</div>
	</div>
<p class="clr"></p>
</div>
<!--end main-->
<p class="clr"></p>
<!--foot-->
<?php Yaf_Loader::import(PATH_VIEW . '/include/foot.phtml');?>
<!--end foot-->
</body>
</html>