<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <base target="_blank">
        <title><?= isset($title) ? $title . '_' . $config['sitename'] : SITENAME ?></title>
        <meta name="keywords" content="<?= isset($keywords) ? misc::remove_nbsp($keywords) : (isset($config['keywords']) ? misc::remove_nbsp($config['keywords']) : '') ?>" />
        <meta name="Description" content="<?= isset($description) ? misc::remove_nbsp($description) : (isset($config['description']) ? misc::remove_nbsp($config['description']) : '') ?>" />
        <link rel="stylesheet" href="<?= IMGURL ?>static/css/mtsy.css" />
        <link rel="stylesheet" href="<?= IMGURL ?>static/css/mtlb.css" type="text/css"/>
        <script language="javascript" src="<?= IMGURL ?>static/js/jQuery-1.11.0.js"></script>
        <script language="javascript" src="<?= IMGURL ?>static/js/mtxg.js"></script>
        <script src="http://siteapp.baidu.com/static/webappservice/uaredirect.js" type="text/javascript"></script>
        <script type="text/javascript">uaredirect("/<?=SITEDIR?>/m/<?= $category[$data['catid']]['catpath'] ?>/<?= $data['id'] ?>.html");</script>
    </head>

    <body>
        <!--头部-->
        <div class="header">
            <div class="top_bar">
                <div class="mtlogo fll"><a href=""></a></div>
                <div class="mtinfo flr"></div>
            </div>
            <div class="nav">
                <ul>
                    <li class="hover"><a href="/zxzx/kgzy/">空谷足音</a></li>
                    <li><a href="/zxzx/fskn/">福寿康宁</a></li>
                    <li><a href="/zxzx/bksm/">别开生面</a></li>
                    <li><a href="/zxzx/kjak/">阖家安康</a></li>
                    <li><a href="/zxzx/bbbq/">百病不侵</a></li>
                    <li><a href="/zxzx/hdzw/">厚德载物</a></li>
                    <li><a href="/zxzx/bqbn/">不屈不挠</a></li>
                    <li><a href="/zxzx/xgzx/">学贯中西</a></li>
                    <li><a href="/zxzx/wfll/">威风凛凛</a></li>
                    <li><a href="/zxzx/cxtx/">促膝谈心</a></li>
                    <li><a href="/zxzx/tcxd/">赤诚相待</a></li>
                    <li><a href="/zxzx/cgxw/">晨光熹微</a></li>
                </ul>
            </div>
        </div>
        <!--头部 end-->
        <div class="clear"></div>
        <div class="banner" name="rw_banner"><img src="<?= IMGURL ?>static/images/nrbanner.jpg" width="1000" height="310" /></div>
        <div class="main">
            <div class="content">
                <div class="dqwz">你的当前位置：<a href="/zxzx/">首页</a> >
                        <a href="/<?= SITEDIR ?>/<?= $category[$data['catid']]['catpath'] ?>/" HtmlUrl_href="/<?= SITEDIR ?>/<?= $category[$data['catid']]['catpath'] ?>/">
                            <?= $category[$data['catid']]['catname'] ?>
                        </a> > <?= $data['title'] ?>
                </div>
                <div class="con_right">
                    <div class="gawimg1" name="rw_youce"><img src="<?= IMGURL ?>static/images/gg_img01.jpg"  width="300" height="315"/></div>
                    <div class="gawimg2" name="rw_youce1"><img src="<?= IMGURL ?>static/images/gg_img02.jpg" width="300" height="150"/></div>
                    <div class="gawimg3" name="rw_youce2"><img src="<?= IMGURL ?>static/images/gg_img03.jpg" width="300" height="125"/></div>
                    <div class="zxwz">
                        <p>最新文章</p>
                        <div name="yltoplb">
                            <ul>
                                <?php foreach ($data['zxwz'] as $v) : ?>
                                <li><a href="/<?= SITEDIR . '/' . $category[$v['catid']]['catpath'] . '/' . $v['id'] . '.html' ?>"><?= mb_substr($v['title'], 0, 20); ?></a></li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                    </div>
                    <div class="zxwz">
                        <p>推荐文章</p>
                        <div name="ylbtlb">
                        </div>
                    </div>
                </div>
                <div class="con_left">
                    <div class="article">
                        <h1><?= $data['title'] ?></h1>
                        <div class="ly">
                           <span>来源：<a href="/<?= SITEDIR ?>/lywz/<?= date('Y-m-d', $data['inputtime']) ?>.html"><?= isset($data['fromweb']) && $data['fromweb'] ? $data['fromweb'] : '本站' ?></a></span>
                            <span>编辑：<a href="/<?= SITEDIR ?>/zxyd/">其他</a></span>
                            <span>发布时间：<?= date('Y-n-j H:i:s', $data['inputtime']) ?></span>
                        </div>
                        <div class="article_top" name="rw_touxia"><img src="<?=IMGURL?>static/images/gg_img04.jpg" width="660" height="100" /></div>
                        <?= isset($data['content']) ? misc::replacebr(stripslashes($data['content'])) : misc::replacebr(stripslashes($data['description'])); ?>
                        <div class="tag">关键词：</div>
                        <div class="sxp clearfix">
                            <p class="sp"><img src="<?= IMGURL ?>static/images/spbj.png" /><?= $data['prenext']['previous'] ?></p>
                            <p class="xp"><?= $data['prenext']['next'] ?><img src="<?= IMGURL ?>static/images/xpbj.png" /></p>
                        </div>
                    </div>
                    <div class="clear"></div>
                    <span><?= misc::uid($data['inputtime'])?></span>
                    <div class="clear"></div>
                    <div class="article_bottom">
                        <p>声明：文章内容仅供参考，具体治疗及选购请咨询医生或相关专业人士。您若对该稿件内容有任何疑问或质疑，请即与久久养生最新资讯联系，本网将迅速给您回应并做处理。电话：010-57031801</p>
                    </div>
                    <div class="clear"></div>
                    <div class="news">
                        <p>最新资讯</p>
                        <ul class="clearfix">
                            <?php foreach ($data['zxzx'] as $v) : ?>
                            <li><a href="/<?= SITEDIR . '/' . $category[$v['catid']]['catpath'] . '/' . $v['id'] . '.html' ?>"><?= mb_substr($v['title'], 0, 20); ?></a></li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                </div>
                
            </div>
        </div>
        <div class="clear"></div>
        <?php Yaf_Loader::import(PATH_VIEW . '/footer.phtml');?>