<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<base target="_blank">
<title>分诊自测-搜狐健康</title>
<link href="<?=IMGURL?>static/home/css/style_s.css" rel="stylesheet" type="text/css" />
<link href="<?=IMGURL?>static/home/css/shindex.css" rel="stylesheet" type="text/css" />
<link href="<?=IMGURL?>static/home/js/jquery.vector-map.css" media="screen" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="<?=IMGURL?>static/home/js/jquery-1.8.3.min.js"></script>
<script type="text/javascript" src="<?=IMGURL?>static/home/js/lowsjs.js"></script>
<script type="text/javascript" src="<?=IMGURL?>static/home/js/kstops.js"></script>
<script src="<?=IMGURL?>static/home/js/jquery.vector-map.js" type="text/javascript"></script>
<script src="<?=IMGURL?>static/home/js/china-zh.js" type="text/javascript"></script>
<script type="text/javascript" src="http://cbjs.baidu.com/js/m.js"></script>
</head>
<body>
<!--head-->
<?php Yaf_Loader::import(PATH_VIEW . '/include/head.phtml');?>
<!--end head-->
<p class="clr"></p>
<!--main-->
<div class="main">
<p class="clr"></p>
<p class="clr"></p>
<div class="zh-2">
<div class="zh-l" style="height:690px;">


<div class="zh-2l" >
<div class="zh-3la"><span>分诊<a>自测</a></span></div>
<div class="zh-2lb">
<iframe id="ifr" src="/Diagnose/cs?id=<?=$id?>" style="width:676px;height:542px;" frameborder=0 style="margin-top:10px;margin-left:1px;"></iframe>
</div>
</div>

</div>
<div class="zh-r">

<div class="zh-2r">
<div class="zh-2ra"><span><a>HOT</a>医院</span></div>
<div class="zh-2rb">
<ul><script type="text/javascript">BAIDU_CLB_fillSlot("836437");</script>
</ul>
</div>
</div>

<div class="zh-2r">
<div class="zh-2ra"><span><a>健康</a>大讲堂</span></div>
<div class="zh-2rc">
<script type="text/javascript">BAIDU_CLB_fillSlot("836446");</script>
</div>
</div>



</div>
</div>
</div>
<!--end main-->
<p class="clr"></p>
<!--foot-->
<?php Yaf_Loader::import(PATH_VIEW . '/include/foot.phtml');?>
<!--end foot-->
</body>
</html>
