<div class="footer">
  <div class="footerinfo">
    <p class="ftinfo1"><a>关于本站</a>|<a>媒体合作</a>|<a>广告招商</a>|<a>版权声明</a>|<a>联系我们</a>|<a>网站地图</a></p>
    <p><img src="http://js.ufstone.com/images/lianxi3.png" /></p>
    <p> 医学是严谨的，生命是唯一的，因个体差异不同，请勿将本网站信息当做诊疗依据!本网站本着服务于民、健康大众的原则致力于提供正确的、完整的、科学的、严肃的健康服务资讯，但所提供的任何 及治疗方法仅供参考，不能替代专业医务人员的建议，如未到医院就医，并未遵照医生诊断和治疗建议，自行使用本网资料发生偏差，本站概不负责，亦不负任何法律责任。凡以任何方式登陆本网站或直接、间接使用本网站资料者，视为自愿接受本网站声明的约束。</p>
  </div>
</div>
</body>
</html>
<?php 
    unset($data);
    DEBUG == 1 && Yaf_Loader::import(PATH_VIEW . '/footer_debug.phtml');
?>