<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<base target="_blank">
<title><?=$title['title']?></title>
<meta name="keywords" content="<?=$title['keyword']?>"/>
<meta name="description" content="<?=$title['description']?>"/>
<link href="<?=IMGURL?>static/home/css/style_s.css" rel="stylesheet" type="text/css" />
<link href="<?=IMGURL?>static/home/css/shindex.css" rel="stylesheet" type="text/css" />
<link href="<?=IMGURL?>static/home/css/shlist.css" rel="stylesheet" type="text/css" />
<link href="<?=IMGURL?>static/home/js/jquery.vector-map.css" media="screen" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="<?=IMGURL?>static/home/js/jquery-1.8.3.min.js"></script>
<script src="http://int.dpool.sina.com.cn/iplookup/iplookup.php?format=js"></script>
<script src="<?=IMGURL?>static/home/js/jquery.vector-map.js" type="text/javascript"></script>
<script src="<?=IMGURL?>static/home/js/china-zh.js" type="text/javascript"></script>
<script type="text/javascript" src="http://cbjs.baidu.com/js/m.js"></script>
</head>
<body>
<!--head-->
<script src="<?=IMGURL?>static/home/js/header.js" type="text/javascript"></script>
<script type="text/javascript" src="<?=IMGURL?>static/home/js/nav.js"></script>
<!--end head-->

<div class='main'>
<?php Yaf_Loader::import(PATH_VIEW . '/include/liucheng.phtml');?>
<div class="lb-1">
	<div class="lb-1l" style="width: 900px;">
	<div class="top1">
		<ul>
			<li class="lis2_a" id="Buttons21">医院</li>
			<li class="lis2" id="Buttons22"><a href="/doctor">医生</a></li>
			<li class="post_li" id="post"><p>为您找到<span class="post_p"><?php if($key){echo $key;}else{echo $department;}?></span>的相关医院</p></li>
		</ul>
		<div id="ContentBoxs21"></div>
		<div style="display:none;" id="ContentBoxs22"></div>
	</div>
		<div class="top3">
			<div id="ContentBoxsa21">
				<div class="lb-a">
				<div class="la">所在地区：</div>
				<p style="width:auto;" id="dqlist">
					<a href="?provinceId=&hospitalLevel=<?=$hospitalLevel?>" class="<?php if($provinceId==false){echo 'focus';}?>">不限</a>
					<a href="?provinceId=2&hospitalLevel=<?=$hospitalLevel?>" class="<?php if($provinceId==2){echo 'focus';}?>">上海</a>
					<a href="?provinceId=22&hospitalLevel=<?=$hospitalLevel?>" class="<?php if($provinceId==22){echo 'focus';}?>">江苏</a>
					<a href="?provinceId=1&hospitalLevel=<?=$hospitalLevel?>" class="<?php if($provinceId==1){echo 'focus';}?>">北京</a>
					<a href="?provinceId=29&hospitalLevel=<?=$hospitalLevel?>" class="<?php if($provinceId==29){echo 'focus';}?>">广东</a>
					<a href="?provinceId=9&hospitalLevel=<?=$hospitalLevel?>" class="<?php if($provinceId==9){echo 'focus';}?>">陕西</a>
					<a href="?provinceId=3&hospitalLevel=<?=$hospitalLevel?>" class="<?php if($provinceId==3){echo 'focus';}?>">天津</a>
					<a href="?provinceId=19&hospitalLevel=<?=$hospitalLevel?>" class="<?php if($provinceId==19){echo 'focus';}?>">湖北</a>
					<a href="?provinceId=8&hospitalLevel=<?=$hospitalLevel?>" class="<?php if($provinceId==8){echo 'focus';}?>">山西</a>
					<a href="?provinceId=23&hospitalLevel=<?=$hospitalLevel?>" class="<?php if($provinceId==23){echo 'focus';}?>">安徽</a>
					<a href="?provinceId=4&hospitalLevel=<?=$hospitalLevel?>" class="<?php if($provinceId==4){echo 'focus';}?>">重庆</a>
					<a href="?provinceId=27&hospitalLevel=<?=$hospitalLevel?>" class="<?php if($provinceId==27){echo 'focus';}?>">福建</a>
					<a href="?provinceId=11&hospitalLevel=<?=$hospitalLevel?>" class="<?php if($provinceId==11){echo 'focus';}?>">甘肃</a>
					<a href="?provinceId=31&hospitalLevel=<?=$hospitalLevel?>" class="<?php if($provinceId==31){echo 'focus';}?>">广西</a>
					<a href="?provinceId=18&hospitalLevel=<?=$hospitalLevel?>" class="<?php if($provinceId==18){echo 'focus';}?>">贵州</a>
					<a href="?provinceId=32&hospitalLevel=<?=$hospitalLevel?>" class="<?php if($provinceId==32){echo 'focus';}?>">海南</a>
					<a href="?provinceId=16&hospitalLevel=<?=$hospitalLevel?>" class="<?php if($provinceId==16){echo 'focus';}?>">河北</a>
					<a href="?provinceId=20&hospitalLevel=<?=$hospitalLevel?>" class="<?php if($provinceId==20){echo 'focus';}?>">河南</a>
					<a href="?provinceId=7&hospitalLevel=<?=$hospitalLevel?>" class="<?php if($provinceId==7){echo 'focus';}?>">黑龙江</a>
					<a href="?provinceId=30&hospitalLevel=<?=$hospitalLevel?>" class="<?php if($provinceId==30){echo 'focus';}?>">湖南</a>
					<a href="?provinceId=6&hospitalLevel=<?=$hospitalLevel?>" class="<?php if($provinceId==6){echo 'focus';}?>">吉林</a>
					<a href="?provinceId=25&hospitalLevel=<?=$hospitalLevel?>" class="<?php if($provinceId==25){echo 'focus';}?>">江西</a>
					<a href="?provinceId=5&hospitalLevel=<?=$hospitalLevel?>" class="<?php if($provinceId==5){echo 'focus';}?>">辽宁</a>
					<a href="?provinceId=33&hospitalLevel=<?=$hospitalLevel?>" class="<?php if($provinceId==33){echo 'focus';}?>">内蒙古</a>
					<a href="?provinceId=10&hospitalLevel=<?=$hospitalLevel?>" class="<?php if($provinceId==10){echo 'focus';}?>">宁夏</a>
					<a href="?provinceId=12&hospitalLevel=<?=$hospitalLevel?>" class="<?php if($provinceId==12){echo 'focus';}?>">青海</a>
					<a href="?provinceId=21&hospitalLevel=<?=$hospitalLevel?>" class="<?php if($provinceId==21){echo 'focus';}?>">山东</a>
					<a href="?provinceId=15&hospitalLevel=<?=$hospitalLevel?>" class="<?php if($provinceId==15){echo 'focus';}?>">四川</a>
					<a href="?provinceId=14&hospitalLevel=<?=$hospitalLevel?>" class="<?php if($provinceId==14){echo 'focus';}?>">西藏</a>
					<a href="?provinceId=13&hospitalLevel=<?=$hospitalLevel?>" class="<?php if($provinceId==13){echo 'focus';}?>">新疆</a>
					<a href="?provinceId=17&hospitalLevel=<?=$hospitalLevel?>" class="<?php if($provinceId==17){echo 'focus';}?>">云南</a>
					<a href="?provinceId=24&hospitalLevel=<?=$hospitalLevel?>"class="<?php if($provinceId==24){echo 'focus';}?>">浙江</a>
				</p>
				</div>
				<div class="lb-a">
				<div class="la">医院科室：</div>
					<p class="selectv" id="kslist">
					<a href="<?=BASEURL.'yy-neike/'?>" class="<?php if($department=='内科'){echo 'focus';}?>">内科</a>
					<a href="<?=BASEURL.'yy-waike/'?>" class="<?php if($department=='外科'){echo 'focus';}?>">外科</a>
					<a href="<?=BASEURL.'yy-fukeyiy/'?>" class="<?php if($department=='妇产科'){echo 'focus';}?>">妇产科</a>
					<a href="<?=BASEURL.'yy-zhongliuke/'?>" class="<?php if($department=='肿瘤科'){echo 'focus';}?>">肿瘤科</a>
					<a href="<?=BASEURL.'yy-xingbingke/'?>" class="<?php if($department=='性病科'){echo 'focus';}?>">性病科</a>
					<a href="<?=BASEURL.'yy-zhuankeyiy/'?>" class="<?php if($department=='皮肤科'){echo 'focus';}?>">皮肤科</a>
					<a href="<?=BASEURL.'yy-tese/'?>" class="<?php if($department=='儿科'){echo 'focus';}?>">儿科</a>
					<a href="<?=BASEURL.'yy-zhongyike/'?>" class="<?php if($department=='中医科'){echo 'focus';}?>">中医科</a>
					<a href="<?=BASEURL.'yy-yanke/'?>" class="<?php if($department=='眼科'){echo 'focus';}?>">眼科</a>
					<a href="<?=BASEURL.'yy-kouqiangke/'?>" class="<?php if($department=='口腔科'){echo 'focus';}?>">口腔科</a>
					<a href="<?=BASEURL.'yy-erbihou/'?>" class="<?php if($department=='耳鼻喉'){echo 'focus';}?>">耳鼻喉</a>
					<a href="<?=BASEURL.'yy-guke/'?>" class="<?php if($department=='骨科'){echo 'focus';}?>">骨科</a>
					</p>
				</div>
				<div class="lb-a">
				<div class="la">医院等级：</div>
					<p class="selectv" id="djlist">
					<a href="?provinceId=" title="不限" class="<?php if($hospitalLevel==false){echo 'focus';}?>">不限</a>
					<a href="?provinceId=<?=$provinceId?>&hospitalLevel=33" class="<?php if($hospitalLevel==33){echo 'focus';}?>">三级甲等</a>
					<a href="?provinceId=<?=$provinceId?>&hospitalLevel=30" class="<?php if($hospitalLevel==30){echo 'focus';}?>">三级医院</a>
					<a href="?provinceId=<?=$provinceId?>&hospitalLevel=20" class="<?php if($hospitalLevel==20){echo 'focus';}?>">二级医院</a>
					<a href="?provinceId=<?=$provinceId?>&hospitalLevel=10" class="<?php if($hospitalLevel==10){echo 'focus';}?>">一级医院</a></p>
				</div>
			</div>
		</div>
	</div>
		
	<div class="lb-1r" style="display: none;">
		<span><?=$department?></span>
		<p id="ksxqlist">
		<?php $n=0;$num = count($disease); for($i=0;$i<$num;$i++){ ?>
			<?php if(strlen($disease[$i]['name'])<=9){?>
				<a href="/Hospital?did=<?=$did?>&department=&key=<?=$disease[$i]['name']?>"><?=$disease[$i]['name']?></a>
				<?php $n++;if($n==12){$i=$num;}?>
			<?php }?>
		<?php } ?>
		</p>
		<div class="lc"><a target="_blank" href="http://disease.guahao.com/department/<?=$did?>" rel="nofollow">更多&gt;&gt;</a></div>
	</div>
</div>

<div class="lb-2">
<?php foreach($hospital as $v){ ?>
<div class="wz-3n">
<div class="wz-3na"><span><a href="/h_<?=$v['id']?>/" ><?=$v['name']?></a></span></div>
<div class="wz-3nb">
<div class="wz-3nc"><a href="/h_<?=$v['id']?>/"  ><img src="<?php if($v['photoUrl']){echo "{$v['photoUrl']}";}else{echo "<?=IMGURL?>static/home/images/hos-l.png";}?>" width="181" height="120" onerror="this.src='<?=IMGURL?>static/home/images/hos-l.png'"  /></a></div>
<ul>
<li><span>医院等级：</span><?=$v['level']?></li>
<li><span>电话：</span><?=$v['tel']?></li>
<li><span>地址：</span><?=$v['address']?></li>
</ul>
<div class="wz-3nd">
<div class="wza"><span class="fenshu"><?=$v['score']?>分数</span>医院评分</div><div class="wza"><span><a href="http://www.guahao.com/commenthospital/commentlist?hospitalId=<?=$v['id']?>" rel="nofollow"><?=$v['evaluteNum']?></a>人</span>评价人次</div>
</div>
<div class="wz-3ne"><a href="http://www.guahao.com/hospital/<?=$v['id']?>" rel="nofollow"><img src="<?=IMGURL?>static/home/img/shlb_131213_45.jpg" width="51" height="40" alt="约门诊" title="约门诊" /></a></div>
</div>
</div>
<?php } ?>
</div>
<script type="text/javascript">
 $(".fenshu:contains('分数')").map(function(){if($(this).text()=="分数")return this;}).html("待评分");
</script>
<div class="page" id="pagebar1">
<?php if($page){echo $page;}?>
</div>
<?php Yaf_Loader::import(PATH_VIEW . '/include/from.phtml');?>
</div>
<p class="clr"></p>
<!--foot-->
<?php Yaf_Loader::import(PATH_VIEW . '/include/foot.phtml');?>
<!--end foot-->
</body>
</html>
