<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=gb2312" />
<base target="_blank">
<title><?=$hospital['name']?>-搜狐健康</title>
<link href="<?=IMGURL?>static/home/css/style_s.css" rel="stylesheet" type="text/css" />
<link href="<?=IMGURL?>static/home/css/shlist.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="<?=IMGURL?>static/home/js/jquery-1.8.3.min.js"></script>
</head>
<body>
<!--head-->
<script src="<?=IMGURL?>static/home/js/header.js" type="text/javascript"></script>
<script type="text/javascript" src="<?=IMGURL?>static/home/js/nav.js"></script>
<!--end head-->
<p class="clr"></p>
<!--main-->
<div class="main">
<?php Yaf_Loader::import(PATH_VIEW . '/include/liucheng.phtml');?>
<style>
#info .content{line-height:20px;padding:20px;}
</style>

<div style="margin-top:15px;clear:both;width:100%;float: left;"><a href="/">首页</a> -> <a href="/h_<?=$hospital['id']?>/"><?=$hospital['name']?></a></div>
<div class="ml" id='info'>

<div class="wz-2l">

<div class="wz-2la">
<div class="wz-2ln"><span><a><?=$news['title']?></a></span></div>
</div>
<div class="wz-2lb">
<div class="content">
<?=$news['content']?>
</div>
</div>


</div>
</div>

<div class="mr">
	<div class="wz-5r">
	<div class="wz-5ra"><span>本院医生<a>一览</a></span></div>
	<div class="wz-5rb">

		<?php foreach($expert as $k=>$v){ ?>
			<div class="wz-5rn">
			<div class="wra"><a href="/h_<?=$v['hospitalId']?>/<?=$v['hdeptId']?>/<?=$v['expertId']?>/"><?=$v['name']?></a><?=$doctorItems[$v['adminTitle']]?> <?=$academicItems[$v['academicType']]?></div>
			<div class="wrb"><img src="<?php if($v['expertPhoto']){echo "{$v['expertPhoto']}";}else{echo "<?=IMGURL?>static/home/images/doc-unknow.png";}?>" width="64" alt="" title="" onerror="this.src='<?=IMGURL?>static/home/images/doc-unknow.png';" /></div>
			<div class="wrc"><p class="picfen">
				<?php
					$fen = ($v['score']/2);
					$ffen = floor($v['score']/2);
					for($i=0;$i<5;$i++){if($i<$ffen){echo "<font class=\"star1\"></font>";}elseif($ffen<$fen && $ffen==$i){echo "<font class=\"star2\"></font>";}else{echo "<font class=\"star3\"></font>";}}?>
			</p><p><span><?=$v['score']?>分</span>/<?=$v['evaluteNum']?>人</p></div>
			<div class="wrd"><span>医院：</span><a href="/h_<?=$v['hospitalId']?>/"><?php echo substr($v['hospitalName'],0,30);?></a></div>
			<div class="wrd"><span>等级：</span><?=$v['hosptialLevel']?></div>
			<div class="wrd"><span>科室：</span><a href="http://www.guahao.com/department/<?=$v['hdeptId']?>"><?=$v['hdeptName']?></a></div>
			<div class="wre"><span>简介：</span><?php echo substr($v['introduction'],0,150);?></div>
			<div class="wrf">
			<a href="http://www.guahao.com/department/shiftcase/<?=$v['hdeptId']?>"><img src="<?=IMGURL?>static/home/img/shlb_131213_52.jpg" width="84" height="26" alt="查看号源" title="查看号源" /></a>
			<a href="http://www.guahao.com/expert/<?=$v['expertId']?>"><img src="<?=IMGURL?>static/home/img/shlb_131213_53.jpg" width="84" height="26" alt="约门诊" title="约门诊" /></a>
			</div>
			</div>
		<?php }?>
		<div class="wzn"></div>
	</div>
	</div>
	<p class="clr"></p>
</div>

<?php Yaf_Loader::import(PATH_VIEW . '/include/from.phtml');?>
</div>
<!--end main-->
<p class="clr"></p>
<!--foot-->
<?php Yaf_Loader::import(PATH_VIEW . '/include/foot.phtml');?>
<!--end foot-->
</body>
</html>
