<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<base target="_blank">
<title>在线咨询_找医院_找医生_查疾病_约门诊_搜狐健康</title>
<meta name="keywords" content="在线咨询,找医院,找医生,查疾病,约门诊,搜狐健康aaaa"/>
<meta name="description" content="搜狐健康是最大的医疗健康咨询平台，您可以在这里在线咨询_找医院_找医生_约门诊_寻找更多专家为您解答，搜狐健康为您提供更多医疗健康信息查询."/>
<link href="<?=IMGURL?>static/home/css/style_s.css" rel="stylesheet" type="text/css" />
<link href="<?=IMGURL?>static/home/css/shindex.css" rel="stylesheet" type="text/css" />
<link rel="stylesheet" type="text/css" href="<?=IMGURL?>static/home/css/tpynx_con_list_1011.css"/>
<link href="<?=IMGURL?>static/home/js/jquery.vector-map.css" media="screen" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="<?=IMGURL?>static/home/js/jquery-1.8.3.min.js"></script>
<script src="http://int.dpool.sina.com.cn/iplookup/iplookup.php?format=js"></script>
<script src="<?=IMGURL?>static/home/js/jquery.vector-map.js" type="text/javascript"></script>
<script src="<?=IMGURL?>static/home/js/china-zh.js" type="text/javascript"></script>
<script type="text/javascript" src="http://cbjs.baidu.com/js/m.js"></script>
</head>
<body>

<!--head-->
<script src="<?=IMGURL?>static/home/js/header.js" type="text/javascript"></script>
<script type="text/javascript" src="<?=IMGURL?>static/home/js/nav.js"></script>
<!--end head-->
<p class="clr"></p>

<!--main-->
<div class="main">
<div style="background-color: #CFEDF8;" class="nav1">
<p>
<?php foreach($navlist as $v){?>
<a href="<?=BASEURL?><?=$v['catpath']?>/"><?=$v['catname']?></a>
<?php } ?>
</p>
</div>
<div class="zh-1">
<div class="zh-1l">
<div class="zh-1la"><span><a>按疾病</a>找医院</span></div>
<div class="zh-1lb">
<div class="zh-1lc">
<div class="zh-1na" id='nk'>
<div class="zha">内</div><div class="zhb">内科</div>
<p><a href="/yy-weiyan/">胃炎</a>
<a href="/yy-jiakang/">甲亢</a>
<a href="/yy-guanxinbing/">冠心病</a>
<a href="/yy-ganyinghua/">肝硬化</a>
<a href="/yy-dx/">癫痫</a>
<a href="/yy-tangniaobing/">糖尿病</a><br />
<a href="/yy-shimianzheng/">失眠</a>
<a href="/yy-xiaochuan/">哮喘</a>
<a href="/yy-feiyan/">肺炎</a>
<a href="/yy-qiguanyan/">气管炎</a>
<a href="/yy-gaoxueya/">高血压</a>
<a href="/yy-huxineike/">鼾症</a><br />
<a href="/yy-jiujinggan/">酒精性肝病</a>
<a href="/yy-xiaohuaneike/">消化道出血</a></p>
</div>

<div class="zh-1nb" id=wk>
<div class="zha">外</div><div class="zhb">外科</div>
<p><a href="/yy-ruxianzs/">乳腺增生</a>
<a href="/yy-jiazhuangxianai/">甲状腺瘤</a>
<a href="/yy-xueguanliu/">血管瘤</a>
<a href="/yy-danjieshi/">胆结石</a>
<a href="/yy-jingmaiqzh/">静脉曲张</a>
<a href="/yy-jingzhuibing/">颈椎病</a></p>
</div>

<div class="zh-1nc" id=fck>
<div class="zha">妇</div><div class="zhb">妇产科</div>
<p><a href="/yy-yuejingbt/">月经不调</a>
<a href="/yy-zigongjl/">子宫肌瘤</a>
<a href="/yy-luanchaonz/">卵巢囊肿</a>
<a href="/yy-gongwaiyun/">宫外孕</a>
<a href="/yy-yunyu/">不孕不育</a><br />
<a href="/yy-fukeyiy/">产后出血</a>
<a href="/yy-luanchaoxingby/">多囊卵巢</a>
<a href="/yy-fukeyiy/">早孕反应</a>
<a href="/yy-yindaoyan/">阴道炎</a>
<a href="/yy-liuchan/">流产</a></p>
</div>

<div class="zh-1nc" id=ek>
<div class="zha">儿</div><div class="zhb">儿科</div>
<p><a href="/yy-xiaoerxc/">小儿哮喘</a>
<a href="/yy-xiaoerdx/">小儿癫痫</a>
<a href="/yy-xiaoercdz/">小儿抽动症</a>
<a href="/yy-xzs/">性早熟</a><br />
<a href="/yy-shouzukoubing/">手足口病</a>
<a href="/yy-xiaoerfx/">小儿腹泻</a>
<a href="/yy-xiaoerddzh/">小儿多动症</a>
<a href="/yy-xiaoerfy/">新生儿肺炎</a></p>
</div>

<div class="zh-1nb" id='pfk'>
<div class="zha">皮</div><div class="zhb">皮肤科</div>
<p><a href="/yy-shizhen/">湿疹</a>
<a href="/yy-baidianfeng/">白癜风</a>
<a href="/yy-yinxuebing/">银屑病</a>
<a href="/yy-xunmazhen/">荨麻疹</a>
<a href="/yy-tuofa/">脱发</a>
<a href="/yy-cuochuang/">痤疮</a></p>
</div>

</div>
<div class="zh-1ld"><a href="/Hospital"><img src="<?=IMGURL?>static/home/img/shlb_131213_68.jpg" width="52" height="18" alt="更多" /></a></div>
</div>
</div>
<div class="zh-1m">
<div class="zh-1ma">
<div style="display: none;" id="conts11">
<a href="http://health.sohu.com/shipin/" rel="nofollow"><img width="320" height="360" title="浓缩的营养" alt="浓缩的营养" src="<?=IMGURL?>static/home/images/hd_01.jpg"></a>

</div>
<div style="display: block;" id="conts12">
<a href="http://health.sohu.com/yaopin/" rel="nofollow"><img width="320" height="360" title="药品安全小知识" alt="药品安全小知识" src="<?=IMGURL?>static/home/images/hd_02.jpg"></a>

</div>
<div style="display: none;" id="conts13">
<a href="http://health.sohu.com/s2013/zhifanggan/" rel="nofollow"><img width="320" height="360" title="教你几招赶走脂肪" alt="教你几招赶走脂肪" src="<?=IMGURL?>static/home/images/hd_03.jpg"></a>
</div>
</div>
<ul id="slips1">
<li class="ls_a1" onmouseover="slipds(1,1)"></li>
<li class="ls_b1" onmouseover="slipds(1,2)"></li>
<li class="ls_b1" onmouseover="slipds(1,3)"></li>
</ul>
</div>
<div class="zh-1r">
<div class="zh-1ra"><span><a>症状</a>自测</span></div>
<div class="zh-1rb">
<div class="zh-1lc">

<div class="zh-1rn">
<p><span>体况</span><a href="/Diagnose/test?id=E05706F328495637E040007F01004E42">
						感觉不适</a>| <a
                                href="/Diagnose/test?id=DE4BCDA091AAC592E040007F01000D10">
						疲劳</a>| <a
                                href="/Diagnose/test?id=DE522898C21BE67AE040007F01001C91">
						消瘦</a>|
                            <a href="/Diagnose/test?id=DE4BBCA4CCD4D76DE040007F01000C64">
						发热</a>|
                            <a href="/Diagnose/test?id=E0575F0192EFA137E040007F010052E3">
						肥胖</a>| <a
                                href="/Diagnose/test?id=DE4BBCA4CCB8D76DE040007F01000C64">
						恶心呕吐</a></p>
</div>

<div class="zh-1rn">
<p><span>头胸</span><a href="/Diagnose/test?id=DE3B0BEC4BB44F42E040007F010065F7">
						头痛</a>| <a
                                href="/Diagnose/test?id=DE4BA76C1E942685E040007F01000C62">
						头晕</a>| <a
                                href="/Diagnose/test?id=E125CB4F97DC2935E0400A0AC8644E88">
						咽喉疼痛</a>|
                            <a href="/Diagnose/test?id=DE3A3A56D638A7A2E040007F010060FE">
						咳嗽</a>|
                            <a href="/Diagnose/test?id=DE4BBCA4CD2DD76DE040007F01000C64">
						咳痰</a>|
                            <a href="/Diagnose/test?id=E05706F326B95637E040007F01004E42">
						喘鸣</a>
</p>
</div>

<div class="zh-1rn">
<p><span>眼耳口鼻</span><a href="/Diagnose/test?id=E05675FC7C54104CE040007F0100583D">
						鼻塞流涕</a>| <a
                                href="/Diagnose/test?id=DE4BCDA09149C592E040007F01000D10">
						耳鸣</a>| <a
                                href="/Diagnose/test?id=DE4BCDA09206C592E040007F01000D10">
						流鼻血</a>|
                            <a href="/Diagnose/test?id=DE4BCDA0923BC592E040007F01000D10">
						眼睛红</a>|
                            <a href="/Diagnose/test?id=E055F103DE5ECADDE040007F01005422">
						眼睛干涩</a>|
                            <a href="/Diagnose/test?id=DE4BA76C1EE32685E040007F01000C62">
						眼痛</a>
</p>
</div>

<div class="zh-1rn">
<p><span>腹部</span><a href="/Diagnose/test?id=DE4BCDA09171C592E040007F01000D10">
						便秘</a>| <a
                                href="/Diagnose/test?id=E05706F326E95637E040007F01004E42">
						反酸</a>| <a
                                href="/Diagnose/test?id=E0563F46ABCCF8ABE040007F01006DEB">
						腹泻</a>| <a
                                href="/Diagnose/test?id=E0575F0192C1A137E040007F010052E3">
						胃肠胀气</a>|
                            <a href="/Diagnose/test?id=E05706F327135637E040007F01004E42">
						呕血与黑便</a>| <a
                                href="/Diagnose/test?id=DE4B1B5194E8C97DE040007F01000B06">
						腹痛</a></p>
</div>

<div class="zh-1rn">
<p><span>皮肤</span><a href="/Diagnose/test?id=E05706F3273C5637E040007F01004E42">
						皮肤肿块</a>| <a
                                href="/Diagnose/test?id=E0563F46ABFCF8ABE040007F01006DEB">
						皮肤瘙痒</a>| <a
                                href="/Diagnose/test?id=E05706F3279C5637E040007F01004E42">
						红肿</a>| <a
                                href="/Diagnose/test?id=E0563F46AC23F8ABE040007F01006DEB">
						红斑</a>|
                            <a href="/Diagnose/test?id=E05706F3278E5637E040007F01004E42">
						鳞屑</a>| <a
                                href="/Diagnose/test?id=E05706F3271C5637E040007F01004E42">
						多汗症</a></p>
</div>

</div>
<div class="zh-1ld"><a href="http://health.sohu.com/s2007/7772/s250797093/index.shtml" rel="nofollow"><img src="<?=IMGURL?>static/home/img/shlb_131213_68.jpg" width="52" height="18" alt="更多"  /></a></div>
</div>
</div>
</div>
<p class="clr"></p>
<div class="zh-st"><img src="<?=IMGURL?>static/home/img/shindex_131213_23.jpg" width="951" height="100" alt="" title="" /></div>
<p class="clr"></p>
<div class="zh-2">
<div class="zh-l">

<?php Yaf_Loader::import(PATH_VIEW . '/include/index_dq.phtml');?>
<?php Yaf_Loader::import(PATH_VIEW . '/include/index_zys.phtml');?>

<div class="zh-2l" id="con" style="overflow:hidden;height:336px;">
<div class="zh-3la" ><span>就诊<a>分享</a></span></div>
<ul id='jzfx'>
<li class="zh-3ln">
<a href="http://www.guahao.com/expert/<?= $doctorshare_1['expertId']?>" rel="nofollow" ><img src="<?=IMGURL?>static/home/images/doc-unknow.png" width="75" height="75" alt="" /></a>
<div class="zh-3na"><span>就诊医生：<?= $doctorshare_1['expertName']?></span>(<a href="/h_125336754304601">复旦大学附属华山医院</a>) <font class="day"><?= $doctorshare_1['treatmentAfterday']?>天前</font></div>
<div class="zh-3nb"><?= $doctorshare_1['content']?></div>
</li>
<li class="zh-3ln">
<a href="http://www.guahao.com/expert/<?= $doctorshare_2['expertId']?>" rel="nofollow" ><img src="<?=IMGURL?>static/home/images/doc-unknow.png" width="75" height="75" alt="" /></a>
<div class="zh-3na"><span>就诊医生：<?= $doctorshare_2['expertName']?></span>(<a href="/h_125336070937502">复旦大学附属中山医院</a>) <font class="day"><?= $doctorshare_2['treatmentAfterday']?>天前</font></div>
<div class="zh-3nb"><?= $doctorshare_2['content']?></div>
</li>
<li class="zh-3ln">
<a href="http://www.guahao.com/expert/<?= $doctorshare_3['expertId']?>" rel="nofollow" ><img src="<?=IMGURL?>static/home/images/doc-unknow.png" width="75" height="75" alt="" /></a>
<div class="zh-3na"><span>就诊医生：<?= $doctorshare_3['expertName']?></span>(<a href="/h_5cee04f9-4cc8-4499-a35b-6f37f2dd8a74" >中国人民解放军总医院301医院</a>) <font class="day"><?= $doctorshare_3['treatmentAfterday']?>天前</font></div>
<div class="zh-3nb"><?= $doctorshare_3['content']?></div>
</li>
<li class="zh-3ln">
<a href="http://www.guahao.com/expert/<?= $doctorshare_4['expertId']?>" rel="nofollow" ><img src="http://img.guahao.cn/images/expert/5735f165-1945-41e0-8cd7-cd48cfd5d0ed/elarge_52f8846e-c09f-4aab-b87c-8190463cd832.jpg" width="75" height="75" alt="" /></a>
<div class="zh-3na"><span>就诊医生：<?= $doctorshare_4['expertName']?></span>(<a href="/h_5735f165-1945-41e0-8cd7-cd48cfd5d0ed" >中国人民解放军北京军区总医院</a>) <font class="day"><?= $doctorshare_4['treatmentAfterday']?>天前</font> </div>
<div class="zh-3nb"><?= $doctorshare_4['content']?></div>
</li>
<li class="zh-3ln">
<a href="http://www.guahao.com/expert/<?= $doctorshare_5['expertId']?>" rel="nofollow" ><img src="<?=IMGURL?>static/home/images/doc-unknow.png" width="75" height="75" alt="" /></a>
<div class="zh-3na"><span>就诊医生：<?= $doctorshare_5['expertName']?></span>(<a href="/h_e4d827d9-9175-410d-b6ea-108984eca121" >中国人民武装警察部队总医院</a>) <font class="day"><?= $doctorshare_5['treatmentAfterday']?>天前</font></div>
<div class="zh-3nb"><?= $doctorshare_5['content']?></div>
</li>
</ul>
</div>
<div class="zh-2lb" style="padding:0px;height:3px;"></div>
<script>
var scrtime;
  $("#con").hover(function(){
  clearInterval(scrtime);
 },function(){
 scrtime = setInterval(function(){
  var $ul = $("#con ul");
  var liHeight = $ul.find("li:last").height();
  $ul.animate({marginTop : liHeight+40 +"px"},1000,function(){
  $ul.find("li:last").prependTo($ul)
  $ul.find("li:first").hide();
  $ul.css({marginTop:0});
  $ul.find("li:first").fadeIn(1000);
  }); 
 },3000);
 }).trigger("mouseleave");
 
function TabMove(id,index,count,link)
{
	var defaultCss="kjy";
	var SelectCss="kjy_a";
	for(var n=1;n<=count;n++)
	{
		document.getElementById("Button"+id+n).className=defaultCss;
		document.getElementById("ContentBox"+id+n).style.display='none';
	}
	document.getElementById("Button"+id+index).className=SelectCss;
	document.getElementById("ContentBox"+id+index).style.display='';
	if(link!=null && link!="")document.getElementById("TabLink"+id).href=link;

}
function slipds(cn,n){
var a = document.getElementById("slips"+cn);
var b = a.getElementsByTagName("li");
for(var i=0;i<b.length;i++){
	if(i==(n-1)){
		b[n-1].className="ls_a"+cn;
        document.getElementById("conts"+cn+n).style.display="block";		
		}
		else{
			b[i].className="ls_b"+cn;
			document.getElementById("conts"+cn+(i+1)).style.display="none";	
			}		
	}
}
</script>
</div>
<div class="zh-r">
<div class="zh-2r">
<div class="zh-2ra"><span><a>HOT</a>医院</span></div>
<div class="zh-2rb">
<ul>
<script type="text/javascript">BAIDU_CLB_fillSlot("836437");</script>
</ul>
</div>
</div>
<div class="zh-2r">
<div class="zh-2ra"><span><a>健康</a>大讲堂</span></div>
<div class="zh-2rc">
<script type="text/javascript">BAIDU_CLB_fillSlot("836446");</script>
</div>
</div>

<div class="zh-2r">
<div class="zh-2ra"><span><a>HOT</a>专家</span></div>
<div class="zh-2rc">
<div class="b2rollBox">
<DIV onmouseup='b2ISL_StopUp()' class='b2LeftBotton' onmouseout='b2ISL_StopUp()' onmousedown='b2ISL_GoUp()'><img src="<?=IMGURL?>static/home/img/shindex_131213_43.jpg" width="24" height="47" alt="" /></DIV>
<DIV id='b2ISL_Cont' class='b2Cont'>
<DIV class='b2ScrCont'>
<DIV id='b2List1'>
<!--循环体-->
<script type="text/javascript">BAIDU_CLB_fillSlot("836456");</script>
<!--循环体-->
</DIV>
<DIV id='b2List2'></DIV></DIV></DIV>
<DIV onmouseup='b2ISL_StopDown()' class='b2RightBotton' onmouseout='b2ISL_StopDown()' onmousedown='b2ISL_GoDown()'><img src="<?=IMGURL?>static/home/img/shindex_131213_44.jpg" width="24" height="47" alt="" /></DIV>
</div>
<SCRIPT type='text/javascript' src="<?=IMGURL?>static/home/js/leftroll2.js"></SCRIPT>
</div>
</div>
<div class="zh-2r">
<div class="zh-2ra"><span><a>最新信息</a></span></div>
<div class="zh-2rb">
<ul>
<li><a href="http://guahao.health.sohu.com/dx/r36w.html" target="_blank">成人癫痫病在治疗过程中需要注意什么</a></li>
<li><a href="http://guahao.health.sohu.com/dx/odrq.html" target="_blank">服抗癫痫药物期间患其他疾病的处理</a></li>
<li><a href="http://guahao.health.sohu.com/dx/8klz.html" target="_blank">治疗癫痫最新疗法是什么</a></li>
<li><a href="http://guahao.health.sohu.com/dx/yh22.html" target="_blank">西医如何治疗癫痫</a></li>
<li><a href="http://guahao.health.sohu.com/dx/btkw.html" target="_blank">准确定位癫痫病灶是手术治疗的关键</a></li>
<li><a href="http://guahao.health.sohu.com/dx/zxvj.html" target="_blank">癫痫患者的自我行为纠正法</a></li>
<li><a href="http://guahao.health.sohu.com/dx/1rdn.html" target="_blank">癫痫病都有哪些治疗方法呢</a></li>
<li><a href="http://guahao.health.sohu.com/dx/ic09.html" target="_blank">儿童癫痫的药物治疗有哪些原则</a></li>
<li><a href="http://guahao.health.sohu.com/dx/7x28.html" target="_blank">癫痫病的根治疗法是什么</a></li>
<li><a href="http://guahao.health.sohu.com/dx/d7ef.html" target="_blank">癫痫患者服用苯妥英钠可能出现不良反应</a></li>
<li><a href="http://guahao.health.sohu.com/dx/oqio.html" target="_blank">抗癫痫药物的吸收和影响因素</a></li>
<li><a href="http://guahao.health.sohu.com/dx/xn0t.html" target="_blank">怎么治疗癫痫好</a></li>
<li><a href="http://guahao.health.sohu.com/dx/qaej.html" target="_blank">癫痫病的辅助治疗方法有哪些</a></li>
<li><a href="http://guahao.health.sohu.com/dx/h1ph.html" target="_blank">癫痫病的治疗应该注意什么</a></li>
<li><a href="http://guahao.health.sohu.com/dx/84oq.html" target="_blank">癫痫手术治疗的效果如何</a></li>
<li><a href="http://guahao.health.sohu.com/dx/l30f.html" target="_blank">癫痫病的药物治疗方法是什么</a></li>
<li><a href="http://guahao.health.sohu.com/dx/pjo7.html" target="_blank">治疗小儿癫痫病效果最好的方法是什么</a></li>
<li><a href="http://guahao.health.sohu.com/dx/7lvn.html" target="_blank">癫痫病怎么治疗最好　</a></li>
<li><a href="http://guahao.health.sohu.com/dx/ydoc.html" target="_blank">癫痫患儿如何更换抗癫痫药物</a></li>
<li><a href="http://guahao.health.sohu.com/dx/1ter.html" target="_blank">癫痫病最新治疗方法有什么</a></li>
<li><a href="http://guahao.health.sohu.com/dx/5fvt.html" target="_blank">成年癫痫病最新治疗方法有哪些</a></li>
<li><a href="http://guahao.health.sohu.com/dx/oupo.html" target="_blank">癫痫药物治疗周期为3到17年</a></li>
<li><a href="http://guahao.health.sohu.com/dx/nd9s.html" target="_blank">27岁小孩子癫痫怎么治疗好</a></li>
<li><a href="http://guahao.health.sohu.com/dx/xzm8.html" target="_blank">彻底治疗癫痫病的方法是什么</a></li>
<!--<script type="text/javascript">BAIDU_CLB_fillSlot("836465");</script>-->

</ul>
</div>
</div>

</div>
</div>
<div class="jibing">
	<div class="jb_t">
		<?php for($i=0;$i<14;$i++){?>
			<?php if($i==0){?>
				<a href="/<?=$nav[$i]['catpath']?>/" class="kjy_a" id="Button11" onmousemove="TabMove(1,1,14)"><?php echo substr($nav[$i]['catname'],0,12);?></a>
			<?php }else{?>
				<a href="/<?=$nav[$i]['catpath']?>/" class="kjy" id="Button1<?=$i+1?>" onmousemove="TabMove(1,<?=$i+1?>,14)"><?php echo substr($nav[$i]['catname'],0,12);?></a>
			<?php }?>
		<?php }?>
		<div class="jb" id="ContentBox11">
			<ul>
				<?php for($i=0;$i<count($list[0])-2;$i++){?>
				<li><span><?php echo date('Y-m-d',$list[0][$i]['inputtime']);?></span><a href="/<?=$list[0]['catpath']?>/<?=$list[0][$i]['id']?>.html"><?=$list[0][$i]['title']?></a></li>
				<? } ?>
			</ul>
		</div>
		<div class="jb" id="ContentBox12" style="display:none;">
			<ul>
				<?php for($i=0;$i<count($list[1])-2;$i++){?>
				<li><span><?php echo date('Y-m-d',$list[1][$i]['inputtime']);?></span><a href="/<?=$list[1]['catpath']?>/<?=$list[1][$i]['id']?>.html"><?=$list[1][$i]['title']?></a></li>
				<? } ?>
			</ul>
		</div>
		<div class="jb" id="ContentBox13" style="display:none;">
			<ul>
				<?php for($i=0;$i<count($list[2])-2;$i++){?>
				<li><span><?php echo date('Y-m-d',$list[2][$i]['inputtime']);?></span><a href="/<?=$list[2]['catpath']?>/<?=$list[2][$i]['id']?>.html"><?=$list[2][$i]['title']?></a></li>
				<? } ?>
			</ul>
		</div>
		<div class="jb" id="ContentBox14" style="display:none;">
		  <ul>
	 	 	<?php for($i=0;$i<count($list[3])-2;$i++){?>
			<li><span><?php echo date('Y-m-d',$list[3][$i]['inputtime']);?></span><a href="/<?=$list[3]['catpath']?>/<?=$list[3][$i]['id']?>.html"><?=$list[3][$i]['title']?></a></li>
			<? } ?>
		  </ul>
		</div>
		<div class="jb" id="ContentBox15" style="display:none;">
		  <ul>
	  	 	<?php for($i=0;$i<count($list[4])-2;$i++){?>
			<li><span><?php echo date('Y-m-d',$list[4][$i]['inputtime']);?></span><a href="/<?=$list[4]['catpath']?>/<?=$list[4][$i]['id']?>.html"><?=$list[4][$i]['title']?></a></li>
			<? } ?>
		  </ul>
			</div>
		<div class="jb" id="ContentBox16" style="display:none;">
		  <ul>
			<?php for($i=0;$i<count($list[5])-2;$i++){?>
			<li><span><?php echo date('Y-m-d',$list[5][$i]['inputtime']);?></span><a href="/<?=$list[5]['catpath']?>/<?=$list[5][$i]['id']?>.html"><?=$list[5][$i]['title']?></a></li>
			<? } ?>
		</div>
		<div class="jb" id="ContentBox17" style="display:none;">
		  <ul>
			<?php for($i=0;$i<count($list[6])-2;$i++){?>
			<li><span><?php echo date('Y-m-d',$list[6][$i]['inputtime']);?></span><a href="/<?=$list[6]['catpath']?>/<?=$list[6][$i]['id']?>.html"><?=$list[6][$i]['title']?></a></li>
			<? } ?>
		  </ul>
		</div>
		<div class="jb" id="ContentBox18" style="display:none;">
		  <ul>
			<?php for($i=0;$i<count($list[7])-2;$i++){?>
			<li><span><?php echo date('Y-m-d',$list[7][$i]['inputtime']);?></span><a href="/<?=$list[7]['catpath']?>/<?=$list[7][$i]['id']?>.html"><?=$list[7][$i]['title']?></a></li>
			<? } ?>
		  </ul>
		</div>
		<div class="jb" id="ContentBox19" style="display:none;">
		  <ul>
		   	<?php for($i=0;$i<count($list[8])-2;$i++){?>
			<li><span><?php echo date('Y-m-d',$list[8][$i]['inputtime']);?></span><a href="/<?=$list[8]['catpath']?>/<?=$list[8][$i]['id']?>.html"><?=$list[8][$i]['title']?></a></li>
			<? } ?>
		  </ul>
		</div>
		<div class="jb" id="ContentBox110" style="display:none;">
		  <ul>
		   	<?php for($i=0;$i<count($list[9])-2;$i++){?>
			<li><span><?php echo date('Y-m-d',$list[9][$i]['inputtime']);?></span><a href="/<?=$list[9]['catpath']?>/<?=$list[9][$i]['id']?>.html"><?=$list[9][$i]['title']?></a></li>
			<? } ?>
		  </ul>
		</div>
		<div class="jb" id="ContentBox111" style="display:none;">
		  <ul>
			<?php for($i=0;$i<count($list[10])-2;$i++){?>
			<li><span><?php echo date('Y-m-d',$list[10][$i]['inputtime']);?></span><a href="/<?=$list[10]['catpath']?>/<?=$list[10][$i]['id']?>.html"><?=$list[10][$i]['title']?></a></li>
			<? } ?>
		  </ul>
		</div>
		<div class="jb" id="ContentBox112" style="display:none;">
		  <ul>
			<?php for($i=0;$i<count($list[11])-2;$i++){?>
			<li><span><?php echo date('Y-m-d',$list[11][$i]['inputtime']);?></span><a href="/<?=$list[11]['catpath']?>/<?=$list[11][$i]['id']?>.html"><?=$list[11][$i]['title']?></a></li>
			<? } ?>
		  </ul>
		</div>
		<div class="jb" id="ContentBox113" style="display:none;">
		  <ul>
			<?php for($i=0;$i<count($list[12])-2;$i++){?>
			<li><span><?php echo date('Y-m-d',$list[12][$i]['inputtime']);?></span><a href="/<?=$list[12]['catpath']?>/<?=$list[12][$i]['id']?>.html"><?=$list[12][$i]['title']?></a></li>
			<? } ?>
		  </ul>
		</div>
		<div class="jb" id="ContentBox114" style="display:none;">
		  <ul>
			<?php for($i=0;$i<count($list[13])-2;$i++){?>
			<li><span><?php echo date('Y-m-d',$list[13][$i]['inputtime']);?></span><a href="/<?=$list[13]['catpath']?>/<?=$list[13][$i]['id']?>.html"><?=$list[13][$i]['title']?></a></li>
			<? } ?>
		  </ul>
		</div>
  </div>
</div>
</div>
</div>

<!--end main-->
<p class="clr"></p>

<!--foot-->
<?php Yaf_Loader::import(PATH_VIEW . '/include/foot.phtml');?>
<!--end foot-->
</body>
</html>
