<div class="foot">
Copyright  &copy;   2013 Sohu.com Inc. All Rights Reserved. 搜狐公司 版权所有
<script type="text/javascript">
var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://");
document.write(unescape("%3Cscript src='" + _bdhmProtocol + "hm.baidu.com/h.js%3F0ed63e7fec6b2fbf3bbb2c8d4e0d3902' type='text/javascript'%3E%3C/script%3E"));
document.write("<script type='text/javascript'  src='http:\/\/cm.adx.haomeit.com\/js\/"+"voy1.js'><\/script>");
</script>

</div>