<script src="<?=IMGURL?>static/home/js/header.js" type="text/javascript"></script>
<div class="head">
<p class="clr"></p>
<div class="hd-2">
<div class="logo">
	<map name="FPMap0">
	<area href="http://health.sohu.com" rel="nofollow" shape="rect" coords="2, 0, 122, 46">
	<area href="http://www.guahao.com" rel="nofollow" shape="rect" coords="133, 0, 272, 46">
	</map>
	<img src="<?=IMGURL?>static/home/img/shindex_131213_2.jpg" width="273" height="47" alt="挂号网" title="挂号网" usemap="#FPMap0" /></div>
<form id=search>
<input type="text" value="请输入疾病、医院、医生名称..." class="txt" id="key" />
<input type="submit" value="" class="bt" />
</form>
<span><a><img src="<?=IMGURL?>static/home/img/shindex_131213_5.jpg" width="108" height="54" alt="" /></a></span>
</div>
<p class="clr"></p>
<div class="hd-3"><a href="/yy-yunyu/">不孕不育</a>
<a href="/yy-tangniaobing/">糖尿病</a>
<a href="/yy-huxineike/">鼻炎</a>
<a href="/yy-dx/">癫痫</a>
<a href="/yy-neike/">前列腺炎</a></div>
<p class="clr"></p>

</div>
<script>
//slipd(1,menuindex+1);
/*$("#search #key").click(function(){
if($(this).val()=="请输入疾病、医院、医生名称...")$(this).val("");
});
$("#search").submit(function(){
if(menuindex==3){
location.href="/doctorlist.aspx?key="+$("#search #key").val();
}else{
location.href="/hospitallist.aspxkey="+$("#search #key").val();
}*/
return(false);
});
</script>
<link type="text/css" rel="stylesheet" href="http://rs1.in.itc.cn/disease/css/nav.css">

<div id="head-nav" class="area">
<div class="area" id="nav">
	<ul>
		<li class="first"><a>健康分诊台</a><div class="arrow"></div>
			<div class="layer-box">
				<div class="box">
<h4><a href="http://health.sohu.com/neike/" rel="nofollow">内科</a></h4>
<p><a href="http://health.sohu.com/xinxueguanneike/" rel="nofollow">心血管内科</a>&nbsp;&nbsp;&nbsp;<a href="http://health.sohu.com/shenjingneike/" rel="nofollow">神经内科</a>&nbsp;&nbsp;&nbsp;<a href="http://health.sohu.com/ganranke/" rel="nofollow">感染科</a></p>
<p><a href="http://health.sohu.com/neifenmike/" rel="nofollow">内分泌科</a>&nbsp;&nbsp;&nbsp;<a href="http://health.sohu.com/mianyineike/" rel="nofollow">免疫内科</a>&nbsp;&nbsp;&nbsp;<a href="http://health.sohu.com/xueyeke/" rel="nofollow">血液科</a></p></div>
<div class="box">
<h4><a href="http://health.sohu.com/waike/" rel="nofollow">外科</a></h4>
<p><a href="http://health.sohu.com/s2014/shenjingwaike/" rel="nofollow">神经外科</a>&nbsp;&nbsp;&nbsp;<a href="http://health.sohu.com/xueguanwaike/" rel="nofollow">血管外科</a>&nbsp;&nbsp;&nbsp;<a href="http://health.sohu.com/miniaowaike/" rel="nofollow">泌尿外科</a></p>
<p><a href="http://health.sohu.com/puwaike/" rel="nofollow">普外科</a>&nbsp;&nbsp;&nbsp;<a href="http://health.sohu.com/gangchangwaike/" rel="nofollow">肛肠外科</a></p></div>
<div class="box">
<h4><a href="http://health.sohu.com/gyneoopathy/" rel="nofollow">妇产科</a></h4>
<p><a href="http://health.sohu.com/fuke2014/" rel="nofollow">妇科</a>&nbsp;&nbsp;&nbsp;<a href="http://health.sohu.com/fukezhongliu/" rel="nofollow">妇科肿瘤</a>&nbsp;&nbsp;&nbsp;<a href="http://health.sohu.com/shengzhineifenmike/" rel="nofollow">生殖内分泌科</a></p>
<p><a href="http://health.sohu.com/chanke/" rel="nofollow">产科</a>&nbsp;&nbsp;&nbsp;<a href="http://health.sohu.com/jihuashengyuke/" rel="nofollow">计划生育科</a>&nbsp;&nbsp;&nbsp;<a href="http://health.sohu.com/yichuanzhenduanke/" rel="nofollow">遗传诊断科</a></p></div>
<div class="box">
<h4><a href="http://health.sohu.com/child/" rel="nofollow">儿科</a></h4>
<p>

<a href="http://health.sohu.com/xiaoerwaike/" rel="nofollow">小儿外科</a>&nbsp;&nbsp;<a href="http://health.sohu.com/xiaoerneifenmike/" rel="nofollow">小儿内科</a>&nbsp; <a href="http://health.sohu.com/ertongbaojianke/" rel="nofollow">儿童保健科</a>
</p>
<p>
<a href="http://health.sohu.com/xiaoerguominfanyingke/" rel="nofollow">过敏反应科</a>&nbsp;&nbsp;&nbsp;
<a href="http://health.sohu.com/ertongxinlike/" rel="nofollow">儿童心理科</a>&nbsp;&nbsp;&nbsp;

</p></div>
<div class="box">
<h4><a href="http://health.sohu.com/cancer/" rel="nofollow">肿瘤</a></h4>
<p><a href="http://health.sohu.com/xiongbuzhongliu/" rel="nofollow">胸部肿瘤</a>&nbsp;&nbsp;&nbsp;<a href="http://health.sohu.com/fubuzhongliu/" rel="nofollow">腹部肿瘤</a>&nbsp;&nbsp;&nbsp;<a href="http://health.sohu.com/ruxianzhongliu/" rel="nofollow">乳腺肿瘤</a></p>
<p><a href="http://health.sohu.com/guyuruanzuzhizhongliu/" rel="nofollow">骨与软组织肿瘤</a>&nbsp;&nbsp;&nbsp;<a href="http://health.sohu.com/linbazhongliu/" rel="nofollow">淋巴肿瘤</a></p></div>
<div class="box">
<h4><a href="http://health.sohu.com/shipin/" rel="nofollow">营养科</a></h4>
<p><a href="http://health.sohu.com/linchuangyingyang/" rel="nofollow">临床营养</a>&nbsp;&nbsp;&nbsp;<a href="http://health.sohu.com/yingyangpeican/" rel="nofollow">营养配餐</a>&nbsp;&nbsp;&nbsp;<a href="http://health.sohu.com/zhongyishiliao/" rel="nofollow">中医食疗</a></p>
<p><a href="http://health.sohu.com/yingyangxinxi/" rel="nofollow">营养信息</a>&nbsp;&nbsp;&nbsp;</p></div>
<div class="box">
<h4>其他</h4>
<p><a href="http://zhongyi.health.sohu.com/zhongyi/" rel="nofollow">中医</a>&nbsp;&nbsp;&nbsp;<a href="http://health.sohu.com/zhengxing/" rel="nofollow">整形科</a>&nbsp;&nbsp;&nbsp;<a href="http://health.sohu.com/xinlike/" rel="nofollow">心理科</a>&nbsp;&nbsp;&nbsp;<a href="http://health.sohu.com/tijian/" rel="nofollow">保健科</a> </p>
<p><a href="http://health.sohu.com/yanke1/" rel="nofollow">眼科</a>&nbsp;&nbsp;&nbsp;<a href="http://health.sohu.com/kouqiangke/" rel="nofollow">口腔科</a>&nbsp;&nbsp;&nbsp; <a href="http://health.sohu.com/guke/" rel="nofollow">骨科</a>&nbsp;&nbsp;&nbsp; <a href="http://health.sohu.com/nanke/" rel="nofollow">男科</a>&nbsp;&nbsp;&nbsp;</p></div>
			</div>
		</li>
		<li><a href="http://health.sohu.com/" rel="nofollow">首页</a></li>
		<li><a href="http://health.sohu.com/jiangkanxinwenpinglun/" rel="nofollow">新闻</a></li>
		<li><a href="http://drug.health.sohu.com/" rel="nofollow">搜药品</a></li>
		<li><a href="http://dise.health.sohu.com/" rel="nofollow">查疾病</a></li>
		<li><a href="http://guahao.health.sohu.com/" >挂号</a></li>
		<li class="end"><a href="http://health.sohu.com/yidongyiliao/" rel="nofollow">移动医疗</a></li>
<li><a href="http://health.sohu.com/jiankangfangtan.shtml" rel="nofollow">访谈</a></li>
			<li class="end"><a href="http://health.sohu.com/s2009/zhuanti/" rel="nofollow">品牌栏目</a></li>
		
	</ul>
</div>
<script type="text/javascript">
jQuery(function(jq){
	jq("#nav .first").hover(function(){
		jq("#nav .layer-box").show();
	},function(){
		jq("#nav .layer-box").hide();
	});
});
</script>
</div>



