<div class="zh-1">
<div class="zh-1l">
<img src="<?=IMGURL?>static/home/img/shlb_131213_1.jpg" width="282" height="124" alt="" title="" />
</div>
<div class="zh-1r">
<div class="zh-1ra">搜狐健康携手挂号网助您轻松<!--<a>约门诊</a> --><span style="color:#B3D14D; font-size:20px; font-weight:bold; margin:0 4px;">约门诊</span></div>
<div class="zh-1rb">
<span>挂号指南:</span><img src="<?=IMGURL?>static/home/img/shlb_131213_3.jpg" width="22" height="22" /><div class="ra">选择医院</div>
<img src="<?=IMGURL?>static/home/img/shlb_131213_4.jpg" width="22" height="22" /><div class="ra">选择科室</div>
<img src="<?=IMGURL?>static/home/img/shlb_131213_5.jpg" width="22" height="22" /><div class="ra">选择日期</div>
<img src="<?=IMGURL?>static/home/img/shlb_131213_6.jpg" width="22" height="22" /><div class="ra">确认预约</div>
<img src="<?=IMGURL?>static/home/img/shlb_131213_7.jpg" width="22" height="22" /><div class="rb">医院取号</div>
</div>
</div>
</div>
