<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<base target="_blank">
<title><?=$doctor['name']?>-<?=$doctor['hdeptName']?>-约门诊_搜狐健康</title>
<link href="<?=IMGURL?>static/home/css/style_s.css" rel="stylesheet" type="text/css" />
<link href="<?=IMGURL?>static/home/css/shlist.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="<?=IMGURL?>static/home/js/jquery-1.8.3.min.js"></script>
<script type="text/javascript" src="http://cbjs.baidu.com/js/m.js"></script>
</head>
<body>
<!--head-->
<script src="<?=IMGURL?>static/home/js/header.js" type="text/javascript"></script>
<script type="text/javascript" src="<?=IMGURL?>static/home/js/nav.js"></script>
<!--end head-->
<p class="clr"></p>
<!--main-->
<div class="main">
<?php Yaf_Loader::import(PATH_VIEW . '/include/liucheng.phtml');?>
<p class="clr"></p>
<div class="wz-1"><div class="wz-1a">
<div class="wz-1l">
<div class="wz-1la">
<img src="<?php if(!empty($doctor['expertPhoto'])){echo "{$doctor['expertPhoto']}";}else{echo "<?=IMGURL?>static/home/images/doc-unknow.png";}?>" onerror="this.src='<?=IMGURL?>static/home/images/doc-unknow.png';"  width="128"  title="" />
<div class="ya"><?=$doctor['name']?><a><?=$doctorItems[$doctor['adminTitle']]?> <?=$academicItems[$doctor['academicType']]?></a></div>
<div class="yb"><span>医院：</span><a href="/h_<?=$doctor['hospitalId']?>/" ><?=$doctor['hospitalName']?></a></div>
<div class="yc" style="display:none"><span>其他坐诊医院：</span></div>
<div class="yd"><span>科室：</span><a href="http://www.guahao.com/department/<?=$doctor['hdeptId']?>" rel="nofollow"><?=$doctor['hdeptName']?></a></div>
<div class="ye"><span>简介：</span><?=$doctor['introduction']?></div>
</div>
<div class="more"><a onclick="morebutton();return(false)" href="" >查看更多>></a></div>
<div class="wz-1lb">
<span>我擅长的疾病：</span>
<p><?=$doctor['specialties']?></p>
<div class="wz-1lc">
<a href="http://www.guahao.com/department/shiftcase/<?=$deptId?>" rel="nofollow"><img src="<?=IMGURL?>static/home/img/shlb_131213_28.jpg" width="84" height="26" alt="查看号源" title="查看号源" /></a>
<a href="http://www.guahao.com/expert/<?=$id?>" rel="nofollow"><img src="<?=IMGURL?>static/home/img/shlb_131213_29.jpg" width="84" height="26" alt="约门诊" title="约门诊" /></a>
</div>
<script>
if("<?=$doctor['state']?>"=="1")$(".wz-1lc").hide();
</script>
</div>
</div>

<div class="wz-1r">
<span>预约规则:</span>
<p><?php echo substr($rule['rule'],0,610);?><a href="http://www.guahao.com/hospital/desc/<?=$hospitalId?>" rel="nofollow">[详情]</a>
</p>
</div>

</div>

<div class="wz-1b"></div>
</div>
<script>
	var height=$(".wz-1la .ye").height()+80;
	if($('.wz-1la').height()>height)$(".wz-1l .more").hide();
</script>
<p class="clr"></p>
<div class="wz-2">
<div class="wz-2l">
<div class="wz-2la">
<div class="wz-2ln">
<span><a>就医</a>分享</span><p><a href="http://www.guahao.com/commentslist/e-<?=$id?>/1-0" rel="nofollow">更多></a></p></div>
</div>

<div class="wz-2lb">
<?php foreach($share as $k=>$v){ ?>
<?php if($k<5){?>
<div class="wz-2lc">
<div class="wz-2a">
<span>就诊原因：<a href="Hospital?did=&department=&key=<?=$v['diseaseReason']?>"><?=$v['diseaseReason']?></a></span>
<p><?=$v['content']?></p>
<div class="wa"><strong><?=$v['nickName']?></strong>于 <?=$v['gmtCreated']?> (就诊后<?=$v['treatmentAfterday']?>天) 评价</div>
<a href=""><img src="<?=IMGURL?>static/home/img/shlb_131213_30.jpg" width="56" height="16" alt="诊后分享" /></a>
</div>
<div class="wz-2b">
<p><span>疗效：</span><?=$effect[$v['treatmentEffect']]?><span>态度：</span><?=$attitude[$v['doctorAttitude']]?></p>
<div class="wb"><a href="http://www.guahao.com/commentexpert/setuseful/<?=$v['id']?>" rel="nofollow">有用</a></div>
</div>
</div>
<?php }} ?>
</div>

</div>
<script>
var morebutton=function(){
	var height=$(".wz-1la .ye").height()+80;
	if($('.wz-1la').height()<height){
		$(".wz-1l .more a").html("收起");
	}else{
		height=140;
		$(".wz-1l .more a").html("查看更多>>");
	}
	$('.wz-1la').animate({height:height+'px'},function(){});
}
if($(".wz-2l .wz-2lc").length==0){
	$(".wz-2l").hide();
	$("#zhuanjia").hide();
}
</script>
<div class="wz-2r" id="zhuanjia">
<div class="wz-2ra"><span><a>同科室</a>专家</span><p><a href="http://www.guahao.com/department/<?=$deptId?>" class="more" rel="nofollow">更多></a></p></div>
<div class="wz-2rb">

<?php foreach($expert as $v){ ?>
<div class="wz-2rn">
<div class="rna"><a href="/h_<?=$v['hospitalId']?>/<?=$v['hdeptId']?>/<?=$v['expertId']?>/"><img src="<?php if($v['expertPhoto']){echo "{$v['expertPhoto']}";}else{echo "<?=IMGURL?>static/home/images/doc-unknow.png";}?>" width="64" alt="" title="" onerror="this.src='<?=IMGURL?>static/home/images/doc-unknow.png';" /></a></div>
<div class="rnb"><a href="/h_<?=$v['hospitalId']?>/<?=$v['hdeptId']?>/<?=$v['expertId']?>/" ><?=$v['name']?></a><?=$doctorItems[$v['adminTitle']]?> <?=$academicItems[$v['academicType']]?></div>
<div class="rnc">
<p class="picfen">
<?php
	$fen = ($v['score']/2);
	$ffen = floor($v['score']/2);
	for($i=0;$i<5;$i++){if($i<$ffen){echo "<font class=\"star1\"></font>";}elseif($ffen<$fen && $ffen==$i){echo "<font class=\"star2\"></font>";}else{echo "<font class=\"star3\"></font>";}}?>
	</p><p><span><?=$v['score']?>分</span>/<?=$v['evaluteNum']?>人</p>
</div>
<div class="rnd">擅长：<?=$v['specialties']?></div>
</div>
<?php } ?>

</div>
</div>
</div>
<p class="clr"></p>
<?php Yaf_Loader::import(PATH_VIEW . '/include/from.phtml');?>
</div>
<!--end main-->
<p class="clr"></p>
<!--foot-->
<?php Yaf_Loader::import(PATH_VIEW . '/include/foot.phtml');?>
<!--end foot-->
</body>
</html>
